import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.Arrays;

public class QFDPrinter {
    public static void main(String[] args) {
        File qfdDirectory = new File(args[0]);
        File[] qfdTypeDirs = qfdDirectory.listFiles();
        if (qfdTypeDirs == null) {
            throw new IllegalArgumentException("Command line argument is not a directory");
        }

        // Alphabetize sub-folders so we get a deterministic read order
        Arrays.sort(qfdTypeDirs, (f1, f2) -> f1.getName().compareTo(f2.getName()));
        for (File qfdTypeDir : qfdTypeDirs) {
            File[] qfdFiles = qfdTypeDir.listFiles();
            if (qfdFiles == null) {
                String fullName  = qfdDirectory.getName() + File.separator + qfdTypeDir.getName();
                throw new IllegalArgumentException(fullName + " is not a directory");
            }

            // Alphabetize QFD files so we get a deterministic read order
            Arrays.sort(qfdFiles, (f1, f2) -> f1.getName().compareTo(f2.getName()));
            for (File qfdFile : qfdFiles) {
                // Ignore CRC checksum files generated by Hadoop
                if (qfdFile.getName().endsWith(".crc")) {
                    continue;
                }

                System.out.println("Reading file " + qfdFile.getName());
                try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(qfdFile))) {
                    QueryFocusedDataSet qfd = (QueryFocusedDataSet) ois.readObject();

                    System.out.println("Request/Reply Matches");
                    for (RequestReplyMatch match : qfd.getMatches()) {
                        System.out.println(match);
                    }


                } catch (IOException e) {
                    throw new RuntimeException("Failed to read file " + qfdFile.getName(), e);
                } catch (ClassNotFoundException e) {
                    // This should never occur
                    throw new RuntimeException("QueryFocusedDataset class not found", e);
                }
            }
        }
    }
}
